
app:
  name: demo
  initial_version: 0.0.1
  artifact: com.example:demo:jar
  source:
    uri: git@github.com:MarcialRosales/concourse-workshop-app1
    branch: master

pipeline:
  emailAddress: mrosales@pivotal.io
  source:
    uri: git@github.com:MarcialRosales/concourse-workshop-ci
    branch: master

  repository:
    uri: http://192.168.1.34:8081/nexus/content/repositories/snapshots

deployment:
  dev:
    pcf:
      space: sandbox
      organization: marcial.rosales@r3pi.io
      skip_cert_check: false

      host: mr-demo
      domain: apps-dev.chdc20-cf.solera.com
