---
resources:
- name: source-code
  type: git
  source:
    uri: {{GIT_URL}}
    branch: master
- name: pcf-resource
  type: cf
  source:
    api: https://api.system-dev.chdc20-cf.solera.com
    username: {{cf-username}}
    password: {{cf-username}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true
jobs:
- name: build-and-verify
  plan:
  - get: source-code
    trigger: true
  - task: build-and-verify
    file: source-code/tasks/build.yml
    params:
      M2_SETTINGS_REPO_ID: {{repo-id}}
      M2_SETTINGS_REPO_USERNAME: {{repo-username}}
      M2_SETTINGS_REPO_PASSWORD: {{repo-password}}
      M2_SETTINGS_REPO_RELEASE_URI: {{repo-release-uri}}
      M2_SETTINGS_REPO_SNAPSHOT_URI: {{repo-snapshot-uri}}
  - put: pcf-resource
    params:
      manifest: source-code/manifest.yml
      path: build-artifact/*.jar